### ISSUE TITLE
Pod install --deployment breaks

### ISSUE THREAD

**Issue by influx6** [unimodules/react-native-unimodules#115]
After installing unimodules (following these [install instructions](https://github.com/unimodules/react-native-unimodules#-installation)) and everything is working fine 🎉
I get no errors with pod install

But when I run pod install --deployment it fails with this message

```
Detected React Native module pods for BVLinearGradient, RNCAsyncStorage, RNCPushNotificationIOS, RNDeviceInfo, RNFS, RNFastImage, RNGoogleSignin, RNI18n, RNImageCropPicker, RNLocalize, RNSVG, RNShare, RNVectorIcons, ReactNativeDarkMode, ReactNativeExceptionHandler, ReactNativeFabric, RollbarReactNative, TouchID, instabug-reactnative, lottie-ios, lottie-react-native, react-native-blur, react-native-branch, react-native-config, react-native-fbsdk, react-native-idfa, react-native-netinfo, react-native-onesignal, react-native-spinkit, react-native-splash-screen, react-native-video, react-native-webview, and rn-fetch-blob
Installing unimodules:
 expo-app-loader-provider@8.0.0 from ../node_modules/expo-app-loader-provider/ios
 expo-constants@8.0.0 from ../node_modules/expo-constants/ios
 expo-file-system@8.0.0 from ../node_modules/expo-file-system/ios
 expo-local-authentication@8.0.0 from ../node_modules/expo-local-authentication/ios
 expo-permissions@8.0.0 from ../node_modules/expo-permissions/ios
 unimodules-barcode-scanner-interface@5.0.0 from ../node_modules/unimodules-barcode-scanner-interface/ios
 unimodules-camera-interface@5.0.0 from ../node_modules/unimodules-camera-interface/ios
 unimodules-constants-interface@5.0.0 from ../node_modules/unimodules-constants-interface/ios
 unimodules-core@5.0.0 from ../node_modules/@unimodules/core/ios
 unimodules-face-detector-interface@5.0.0 from ../node_modules/unimodules-face-detector-interface/ios
 unimodules-file-system-interface@5.0.0 from ../node_modules/unimodules-file-system-interface/ios
 unimodules-font-interface@5.0.0 from ../node_modules/unimodules-font-interface/ios
 unimodules-image-loader-interface@5.0.0 from ../node_modules/unimodules-image-loader-interface/ios
 unimodules-permissions-interface@5.0.0 from ../node_modules/unimodules-permissions-interface/ios
 unimodules-react-native-adapter@5.0.0 from ../node_modules/@unimodules/react-native-adapter/ios
 unimodules-sensors-interface@5.0.0 from ../node_modules/unimodules-sensors-interface/ios
 unimodules-task-manager-interface@5.0.0 from ../node_modules/unimodules-task-manager-interface/ios

Analyzing dependencies
Verifying no changes
[!] There were changes to the podfile in deployment mode:
M EXAppLoaderProvider
M EXConstants
M EXFileSystem
M EXLocalAuthentication
M EXPermissions
M UMBarCodeScannerInterface
M UMCameraInterface
M UMConstantsInterface
M UMCore
M UMFaceDetectorInterface
M UMFileSystemInterface
M UMFontInterface
M UMImageLoaderInterface
M UMPermissionsInterface
M UMReactNativeAdapter
M UMSensorsInterface
M UMTaskManagerInterface
```

Versions
    react: 16.9.0 => 16.9.0
    react-native: 0.61.4 => 0.61.4
    react-native-cli: 2.0.1
    react-native: 0.61.5
    react-native-unimodules@0.7.0

<details>
<summary>Podfile</summary>
<br/>

<p>

```bash
source 'https://cdn.cocoapods.org/'

platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

project 'gini',
    'DebugTESTING' => :debug,
    'DebugQA' => :debug,
    'Debug' => :debug,
    'ReleaseTESTING' => :release,
    'ReleaseQA' => :release,
    'Release' => :release

target 'gini' do
  # Pods for giniApp
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"

  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  use_native_modules!
  use_unimodules!
end

target 'OneSignalNotificationServiceExtensions' do
  pod 'OneSignal', '>= 2.11.2', '< 3.3'
end
```

</p>
</details>

<br/>

<details>
<summary>Full `pod install --deployment --verbose`</summary>
<br/>

<p>

```
pod install --deployment --verbose
Detected React Native module pods for BVLinearGradient, RNCAsyncStorage, RNCPushNotificationIOS, RNDeviceInfo, RNFS, RNFastImage, RNGoogleSignin, RNI18n, RNImageCropPicker, RNLocalize, RNSVG, RNShare, RNVectorIcons, ReactNativeDarkMode, ReactNativeExceptionHandler, ReactNativeFabric, RollbarReactNative, TouchID, instabug-reactnative, lottie-ios, lottie-react-native, react-native-blur, react-native-branch, react-native-config, react-native-fbsdk, react-native-idfa, react-native-netinfo, react-native-onesignal, react-native-spinkit, react-native-splash-screen, react-native-video, react-native-webview, and rn-fetch-blob
Installing unimodules:
 expo-app-loader-provider@8.0.0 from ../node_modules/expo-app-loader-provider/ios
 expo-constants@8.0.0 from ../node_modules/expo-constants/ios
 expo-file-system@8.0.0 from ../node_modules/expo-file-system/ios
 expo-local-authentication@8.0.0 from ../node_modules/expo-local-authentication/ios
 expo-permissions@8.0.0 from ../node_modules/expo-permissions/ios
 unimodules-barcode-scanner-interface@5.0.0 from ../node_modules/unimodules-barcode-scanner-interface/ios
 unimodules-camera-interface@5.0.0 from ../node_modules/unimodules-camera-interface/ios
 unimodules-constants-interface@5.0.0 from ../node_modules/unimodules-constants-interface/ios
 unimodules-core@5.0.0 from ../node_modules/@unimodules/core/ios
 unimodules-face-detector-interface@5.0.0 from ../node_modules/unimodules-face-detector-interface/ios
 unimodules-file-system-interface@5.0.0 from ../node_modules/unimodules-file-system-interface/ios
 unimodules-font-interface@5.0.0 from ../node_modules/unimodules-font-interface/ios
 unimodules-image-loader-interface@5.0.0 from ../node_modules/unimodules-image-loader-interface/ios
 unimodules-permissions-interface@5.0.0 from ../node_modules/unimodules-permissions-interface/ios
 unimodules-react-native-adapter@5.0.0 from ../node_modules/@unimodules/react-native-adapter/ios
 unimodules-sensors-interface@5.0.0 from ../node_modules/unimodules-sensors-interface/ios
 unimodules-task-manager-interface@5.0.0 from ../node_modules/unimodules-task-manager-interface/ios

  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-gini`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-OneSignalNotificationServiceExtensions`: (``)

Finding Podfile changes
  M EXAppLoaderProvider
  M EXConstants
  M EXFileSystem
  M EXLocalAuthentication
  M EXPermissions
  M UMBarCodeScannerInterface
  M UMCameraInterface
  M UMConstantsInterface
  M UMCore
  M UMFaceDetectorInterface
  M UMFileSystemInterface
  M UMFontInterface
  M UMImageLoaderInterface
  M UMPermissionsInterface
  M UMReactNativeAdapter
  M UMSensorsInterface
  M UMTaskManagerInterface
  - BVLinearGradient
  - DoubleConversion
  - FBLazyVector
  - FBReactNativeSpec
  - Folly
  - OneSignal
  - RCTRequired
  - RCTTypeSafety
  - RNCAsyncStorage
  - RNCPushNotificationIOS
  - RNDeviceInfo
  - RNFS
  - RNFastImage
  - RNGoogleSignin
  - RNI18n
  - RNImageCropPicker
  - RNLocalize
  - RNSVG
  - RNShare
  - RNVectorIcons
  - React
  - React-Core
  - React-CoreModules
  - React-RCTActionSheet
  - React-RCTAnimation
  - React-RCTBlob
  - React-RCTImage
  - React-RCTLinking
  - React-RCTNetwork
  - React-RCTSettings
  - React-RCTText
  - React-RCTVibration
  - React-cxxreact
  - React-jsi
  - React-jsiexecutor
  - React-jsinspector
  - ReactCommon
  - ReactNativeDarkMode
  - ReactNativeExceptionHandler
  - ReactNativeFabric
  - RollbarReactNative
  - TouchID
  - Yoga
  - glog
  - instabug-reactnative
  - lottie-ios
  - lottie-react-native
  - react-native-blur
  - react-native-branch
  - react-native-config
  - react-native-fbsdk
  - react-native-idfa
  - react-native-netinfo
  - react-native-onesignal
  - react-native-spinkit
  - react-native-splash-screen
  - react-native-video
  - react-native-webview
  - rn-fetch-blob

Fetching external sources
-> Fetching podspec for `BVLinearGradient` from `../node_modules/react-native-linear-gradient`
-> Fetching podspec for `EXAppLoaderProvider` from `../node_modules/expo-app-loader-provider/ios`
-> Fetching podspec for `EXConstants` from `../node_modules/expo-constants/ios`
-> Fetching podspec for `EXFileSystem` from `../node_modules/expo-file-system/ios`
-> Fetching podspec for `EXLocalAuthentication` from `../node_modules/expo-local-authentication/ios`
-> Fetching podspec for `EXPermissions` from `../node_modules/expo-permissions/ios`
-> Fetching podspec for `FBLazyVector` from `../node_modules/react-native/Libraries/FBLazyVector`
-> Fetching podspec for `FBReactNativeSpec` from `../node_modules/react-native/Libraries/FBReactNativeSpec`
-> Fetching podspec for `RCTRequired` from `../node_modules/react-native/Libraries/RCTRequired`
-> Fetching podspec for `RCTTypeSafety` from `../node_modules/react-native/Libraries/TypeSafety`
-> Fetching podspec for `RNCAsyncStorage` from `../node_modules/@react-native-community/async-storage`
-> Fetching podspec for `RNCPushNotificationIOS` from `../node_modules/@react-native-community/push-notification-ios`
-> Fetching podspec for `RNDeviceInfo` from `../node_modules/react-native-device-info`
-> Fetching podspec for `RNFS` from `../node_modules/react-native-fs`
-> Fetching podspec for `RNFastImage` from `../node_modules/react-native-fast-image`
-> Fetching podspec for `RNGoogleSignin` from `../node_modules/@react-native-community/google-signin`
-> Fetching podspec for `RNI18n` from `../node_modules/react-native-i18n`
-> Fetching podspec for `RNImageCropPicker` from `../node_modules/react-native-image-crop-picker`
-> Fetching podspec for `RNLocalize` from `../node_modules/react-native-localize`
-> Fetching podspec for `RNSVG` from `../node_modules/react-native-svg`
-> Fetching podspec for `RNShare` from `../node_modules/react-native-share`
-> Fetching podspec for `RNVectorIcons` from `../node_modules/react-native-vector-icons`
-> Fetching podspec for `React` from `../node_modules/react-native/`
-> Fetching podspec for `React-Core` from `../node_modules/react-native/`
-> Fetching podspec for `React-CoreModules` from `../node_modules/react-native/React/CoreModules`
-> Fetching podspec for `React-RCTActionSheet` from `../node_modules/react-native/Libraries/ActionSheetIOS`
-> Fetching podspec for `React-RCTAnimation` from `../node_modules/react-native/Libraries/NativeAnimation`
-> Fetching podspec for `React-RCTBlob` from `../node_modules/react-native/Libraries/Blob`
-> Fetching podspec for `React-RCTImage` from `../node_modules/react-native/Libraries/Image`
-> Fetching podspec for `React-RCTLinking` from `../node_modules/react-native/Libraries/LinkingIOS`
-> Fetching podspec for `React-RCTNetwork` from `../node_modules/react-native/Libraries/Network`
-> Fetching podspec for `React-RCTSettings` from `../node_modules/react-native/Libraries/Settings`
-> Fetching podspec for `React-RCTText` from `../node_modules/react-native/Libraries/Text`
-> Fetching podspec for `React-RCTVibration` from `../node_modules/react-native/Libraries/Vibration`
-> Fetching podspec for `React-cxxreact` from `../node_modules/react-native/ReactCommon/cxxreact`
-> Fetching podspec for `React-jsi` from `../node_modules/react-native/ReactCommon/jsi`
-> Fetching podspec for `React-jsiexecutor` from `../node_modules/react-native/ReactCommon/jsiexecutor`
-> Fetching podspec for `React-jsinspector` from `../node_modules/react-native/ReactCommon/jsinspector`
-> Fetching podspec for `ReactCommon` from `../node_modules/react-native/ReactCommon`
-> Fetching podspec for `ReactNativeDarkMode` from `../node_modules/react-native-dark-mode`
-> Fetching podspec for `ReactNativeExceptionHandler` from `../node_modules/react-native-exception-handler/ios`
-> Fetching podspec for `ReactNativeFabric` from `../node_modules/react-native-fabric`
-> Fetching podspec for `RollbarReactNative` from `../node_modules/rollbar-react-native`
-> Fetching podspec for `TouchID` from `../node_modules/react-native-touch-id`
-> Fetching podspec for `UMBarCodeScannerInterface` from `../node_modules/unimodules-barcode-scanner-interface/ios`
-> Fetching podspec for `UMCameraInterface` from `../node_modules/unimodules-camera-interface/ios`
-> Fetching podspec for `UMConstantsInterface` from `../node_modules/unimodules-constants-interface/ios`
-> Fetching podspec for `UMCore` from `../node_modules/@unimodules/core/ios`
-> Fetching podspec for `UMFaceDetectorInterface` from `../node_modules/unimodules-face-detector-interface/ios`
-> Fetching podspec for `UMFileSystemInterface` from `../node_modules/unimodules-file-system-interface/ios`
-> Fetching podspec for `UMFontInterface` from `../node_modules/unimodules-font-interface/ios`
-> Fetching podspec for `UMImageLoaderInterface` from `../node_modules/unimodules-image-loader-interface/ios`
-> Fetching podspec for `UMPermissionsInterface` from `../node_modules/unimodules-permissions-interface/ios`
-> Fetching podspec for `UMReactNativeAdapter` from `../node_modules/@unimodules/react-native-adapter/ios`
-> Fetching podspec for `UMSensorsInterface` from `../node_modules/unimodules-sensors-interface/ios`
-> Fetching podspec for `UMTaskManagerInterface` from `../node_modules/unimodules-task-manager-interface/ios`
-> Fetching podspec for `Yoga` from `../node_modules/react-native/ReactCommon/yoga`
-> Fetching podspec for `instabug-reactnative` from `../node_modules/instabug-reactnative`
-> Fetching podspec for `lottie-ios` from `../node_modules/lottie-ios`
-> Fetching podspec for `lottie-react-native` from `../node_modules/lottie-react-native`
-> Fetching podspec for `react-native-blur` from `../node_modules/react-native-blur`
-> Fetching podspec for `react-native-branch` from `../node_modules/react-native-branch`
-> Fetching podspec for `react-native-config` from `../node_modules/react-native-config`
-> Fetching podspec for `react-native-fbsdk` from `../node_modules/react-native-fbsdk`
-> Fetching podspec for `react-native-idfa` from `../node_modules/react-native-idfa`
-> Fetching podspec for `react-native-netinfo` from `../node_modules/@react-native-community/netinfo`
-> Fetching podspec for `react-native-onesignal` from `../node_modules/react-native-onesignal`
-> Fetching podspec for `react-native-spinkit` from `../node_modules/react-native-spinkit`
-> Fetching podspec for `react-native-splash-screen` from `../node_modules/react-native-splash-screen`
-> Fetching podspec for `react-native-video` from `../node_modules/react-native-video`
-> Fetching podspec for `react-native-webview` from `../node_modules/react-native-webview`
-> Fetching podspec for `rn-fetch-blob` from `../node_modules/rn-fetch-blob`

Resolving dependencies of `Podfile`
  CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_c_1_2.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/c/1/2/OneSignal/2.12.6/OneSignal.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_c_8_e.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/c/8/e/Rollbar/1.11.6/Rollbar.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_d_4_0.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/d/4/0/GoogleSignIn/5.0.2/GoogleSignIn.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_d_a_c.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/d/a/c/Branch/0.31.4/Branch.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_6_7_d.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/6/7/d/boost-for-react-native/1.63.0/boost-for-react-native.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_0_a_c.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/0/a/c/Fabric/1.10.2/Fabric.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_3_6_0.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/3/6/0/Crashlytics/3.14.0/Crashlytics.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_a_e_b.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/a/e/b/RSKImageCropper/2.2.3/RSKImageCropper.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_a_5_3.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/a/5/3/QBImagePickerController/3.4.0/QBImagePickerController.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_1_1_7.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/1/1/7/SDWebImage/5.5.2/SDWebImage.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_e_9_d.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/e/9/d/SDWebImageWebPCoder/0.5.0/SDWebImageWebPCoder.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_9_b_5.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/9/b/5/FBSDKCoreKit/6.1.0-alpha/FBSDKCoreKit.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_c_a_b.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/c/a/b/FBSDKShareKit/6.0.0/FBSDKShareKit.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_b_3_c.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/b/3/c/FBSDKLoginKit/6.0.0/FBSDKLoginKit.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/1/1/7/SDWebImage/5.5.2/SDWebImage.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/1/1/7/SDWebImage/5.5.2/SDWebImage.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/3/6/0/Crashlytics/3.14.0/Crashlytics.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/0/a/c/Fabric/1.10.2/Fabric.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/0/a/c/Fabric/1.10.2/Fabric.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/9/b/5/FBSDKCoreKit/5.15.1/FBSDKCoreKit.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/9/b/5/FBSDKCoreKit/5.15.1/FBSDKCoreKit.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/9/b/5/FBSDKCoreKit/5.15.1/FBSDKCoreKit.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/6/7/d/boost-for-react-native/1.63.0/boost-for-react-native.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/6/7/d/boost-for-react-native/1.63.0/boost-for-react-native.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/a/e/b/RSKImageCropper/2.2.3/RSKImageCropper.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/c/1/2/OneSignal/2.11.2/OneSignal.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/a/5/3/QBImagePickerController/3.4.0/QBImagePickerController.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/e/9/d/SDWebImageWebPCoder/0.2.5/SDWebImageWebPCoder.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/1/1/7/SDWebImage/5.5.2/SDWebImage.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_1_9_2.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/1/9/2/libwebp/1.1.0/libwebp.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/c/1/2/OneSignal/2.11.2/OneSignal.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/d/4/0/GoogleSignIn/5.0.2/GoogleSignIn.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_b_b_9.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/b/b/9/AppAuth/1.3.0/AppAuth.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_2_c_c.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/2/c/c/GTMAppAuth/1.0.0/GTMAppAuth.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_c_e_3.txt exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.3.1/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.3.1/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/c/a/b/FBSDKShareKit/5.15.1/FBSDKShareKit.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/c/a/b/FBSDKShareKit/5.15.1/FBSDKShareKit.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/c/8/e/Rollbar/1.5.2/Rollbar.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/b/b/9/AppAuth/1.3.0/AppAuth.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/b/b/9/AppAuth/1.3.0/AppAuth.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/b/b/9/AppAuth/1.3.0/AppAuth.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/2/c/c/GTMAppAuth/1.0.0/GTMAppAuth.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/b/b/9/AppAuth/1.3.0/AppAuth.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/1/9/2/libwebp/1.1.0/libwebp.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/1/9/2/libwebp/1.1.0/libwebp.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/1/9/2/libwebp/1.1.0/libwebp.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/1/9/2/libwebp/1.1.0/libwebp.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/d/a/c/Branch/0.27.1/Branch.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/d/a/c/Branch/0.27.1/Branch.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.3.1/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.3.1/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/b/3/c/FBSDKLoginKit/5.15.1/FBSDKLoginKit.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/b/3/c/FBSDKLoginKit/5.15.1/FBSDKLoginKit.podspec.json exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.3.1/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update

Comparing resolved specification to the sandbox manifest
  - AppAuth
  - BVLinearGradient
  - Branch
  - Crashlytics
  - DoubleConversion
  - EXAppLoaderProvider
  - EXConstants
  - EXFileSystem
  - EXLocalAuthentication
  - EXPermissions
  - FBLazyVector
  - FBReactNativeSpec
  - FBSDKCoreKit
  - FBSDKLoginKit
  - FBSDKShareKit
  - Fabric
  - Folly
  - GTMAppAuth
  - GTMSessionFetcher
  - GoogleSignIn
  - OneSignal
  - QBImagePickerController
  - RCTRequired
  - RCTTypeSafety
  - RNCAsyncStorage
  - RNCPushNotificationIOS
  - RNDeviceInfo
  - RNFS
  - RNFastImage
  - RNGoogleSignin
  - RNI18n
  - RNImageCropPicker
  - RNLocalize
  - RNSVG
  - RNShare
  - RNVectorIcons
  - RSKImageCropper
  - React
  - React-Core
  - React-CoreModules
  - React-RCTActionSheet
  - React-RCTAnimation
  - React-RCTBlob
  - React-RCTImage
  - React-RCTLinking
  - React-RCTNetwork
  - React-RCTSettings
  - React-RCTText
  - React-RCTVibration
  - React-cxxreact
  - React-jsi
  - React-jsiexecutor
  - React-jsinspector
  - ReactCommon
  - ReactNativeDarkMode
  - ReactNativeExceptionHandler
  - ReactNativeFabric
  - Rollbar
  - RollbarReactNative
  - SDWebImage
  - SDWebImageWebPCoder
  - TouchID
  - UMBarCodeScannerInterface
  - UMCameraInterface
  - UMConstantsInterface
  - UMCore
  - UMFaceDetectorInterface
  - UMFileSystemInterface
  - UMFontInterface
  - UMImageLoaderInterface
  - UMPermissionsInterface
  - UMReactNativeAdapter
  - UMSensorsInterface
  - UMTaskManagerInterface
  - Yoga
  - boost-for-react-native
  - glog
  - instabug-reactnative
  - libwebp
  - lottie-ios
  - lottie-react-native
  - react-native-blur
  - react-native-branch
  - react-native-config
  - react-native-fbsdk
  - react-native-idfa
  - react-native-netinfo
  - react-native-onesignal
  - react-native-spinkit
  - react-native-splash-screen
  - react-native-video
  - react-native-webview
  - rn-fetch-blob

Verifying no changes
[!] There were changes to the podfile in deployment mode:
M EXAppLoaderProvider
M EXConstants
M EXFileSystem
M EXLocalAuthentication
M EXPermissions
M UMBarCodeScannerInterface
M UMCameraInterface
M UMConstantsInterface
M UMCore
M UMFaceDetectorInterface
M UMFileSystemInterface
M UMFontInterface
M UMImageLoaderInterface
M UMPermissionsInterface
M UMReactNativeAdapter
M UMSensorsInterface
M UMTaskManagerInterface

/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:465:in `verify_no_podfile_changes!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
/```

</p>

</details>

**Comment by sjchmiela** [comment]
This has been fixed in `react-native-unimodules@0.8.0` 🎉 (https://github.com/unimodules/react-native-unimodules/pull/96)!
