### ISSUE TITLE
an Error occurred while building android

### ISSUE THREAD

**Issue by tranducduong1994** [unimodules/react-native-unimodules#176]
I followed this link to install **react-native-unimodules** in my project: https://docs.expo.dev/bare/installing-unimodules/#configuration-for-android

But terminal threw this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/tranducduong/mobile/android/app/build/intermediates/packaged_manifests/debug/AndroidManifest.xml:184: AAPT: error: resource style/DeviceCredentialHandlerTheme (aka com.cerebral.cerebral:style/DeviceCredentialHandlerTheme) not found.
         

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s

    at makeError (/Users/tranducduong/mobile/node_modules/execa/index.js:174:9)
    at /Users/tranducduong/mobile/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (/Users/tranducduong/mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/Users/tranducduong/mobile/node_modules/@react-native-community/cli/build/index.js:186:9)
```

I followed all of steps in the link, I don't know why this error occured. Thank you.

**Comment by tranducduong1994** [comment]
did the installation instruction miss the "DeviceCredentialHandlerTheme" step?

**Comment by hugoduchene** [comment]
same error

**Comment by koyta** [comment]
is anyone resolved this?

**Comment by hgndgn** [comment]
I have the same issue...

**Comment by hgndgn** [comment]
I updated all the packages with `npm-check-updates` and the build work now.

**Comment by CCB-cerivera** [comment]
The solution to the error is found in the following link:
[[Solution Here](https://savecode.net/code/none/style%2Fdevicecredentialhandlertheme%29+not+found.)]

I copy the solution in case the link is lost:

[YouAPP name/android/app/src/main/AndroidManifest.xml

check the arrival name

chage with this
android:theme="@style/DeviceCredentialHandlerTheme"

and check the app theme name in

YouAPP name/android/app/src/main/res/values/styles.xml
change the name to error theme name its works for me try to run yarn android] Author: By Stone Hammer Danny Reichel at May 04 2021

**Comment by chancesmith** [comment]
same error

**Comment by jamonholmgren** [comment]
For me, running `expo install expo-secure-store` fixed the issue.

https://github.com/expo/expo/issues/17108#issuecomment-1102200109

**Comment by ddinchev** [comment]
@jamonholmgren can you confirm what version did `expo install expo-secure-store` installs for you and if you build on EAS?  For me, it now installs `11.2.0` and the error persists, I have to do `npm install expo-secure-store@11.0.2` to be able to build.
